### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by IAFahim**
where is the eamil via one would contact you

### CODE REVIEW

**Comment by Rak16-nub04** [comment]
Sorry vai
rakibislam65656@gmail.com
nsu mail: rakibul.islam27@northsouth.edu

**Comment by IAFahim** [comment]
> Sorry vai

No no I wanted to help only. No need to apologize.
Pull vhai.
I was shocked seeing ***@***.***
I was like, why is the massage like that. Quite creative.

**Comment by Rak16-nub04** [comment]
> > Sorry vai
> 
> No no I wanted to help only. No need to apologize. Pull vhai. I was shocked seeing _**@**_.*** I was like, why is the massage like that. Quite creative.

replied from mail

**Comment by IAFahim** [comment]
Good good. I mean, Pull come to GitHub and marge the change to your repo.

By hitting marge.
https://github.com/Rak16-nub04/Rak16-nub04/pull/1?new_mergebox=true

_I am assuming you don't know what marge is._

**Pull request merged**
